### ISSUE TITLE
Question about applying ckeckpoint into a real example

### ISSUE THREAD

**Issue by wang-haoxiang** [mveres01/pytorch-drl4vrp#4]
Hi,

Could you please explain more about how to apply the checkpoint into a real example?

Thanks a lot!

**Comment by HuangYanfei** [comment]
Checkpiont is the save dir of trained model, to test on you own instances, you need to transform your instance parameters into the VehicleRoutingDataset class in VRP.py.

**Comment by wang-haoxiang** [comment]
Thanks @HuangYanfei 
In the Readme file, the author says the trained weights are available, so how to use the trained model to train the new sample. I read some materials about checkpoint, but still confused.

**Comment by wang-haoxiang** [comment]
I think I know how to use the checkpoint file. Folder of checkpoint files has the same path with the generated pictures.

**Comment by wang-haoxiang** [comment]
Hi,

I would appreciate it if someone can tell me the correct path of 'actor.pt' and 'critic.pt' to restore checkpoint.

Thanks!

**Comment by mveres01** [comment]
The readme outlines how to restore a checkpoint. If you download the sample weights folder, you can point to a given directory:

```python trainer.py --task=vrp --nodes=10 --checkpoint=sample_weights/vrp10```

If you want to use your own data, as @HuangYanfei mentioned, you will need to replace the `VehicleRoutingDataset` class. You should only need to replace from the __init__ function, and the rest can probably be left as is.

It is important to note however, that data for this problem is generated by sampling uniformly between the interval of [0, 1]. If you are trying to apply a checkpoint **directly** to real-life data that comes from a different distribution, you might get different results, and would likely need to train a model from scratch
